In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/content/ShelterDogs.csv")
df # As dataframe has supervised ML

,ID,name,age,sex,breed,date_found,adoptable_from,posted,color,coat,size,neutered,housebroken,likes_people,likes_children,get_along_males,get_along_females,get_along_cats,keep_in
0,23807,Gida,0.25,female,Unknown Mix,2019-12-10,2019-12-11,2019-12-11,red,short,small,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,533,Frida És Ricsi,0.17,female,Unknown Mix,2019-12-01,2019-12-01,2019-12-09,black and white,short,small,no,NaN,yes,yes,yes,yes,yes,NaN
2,23793,NaN,4.00,male,Unknown Mix,2019-12-08,2019-12-23,2019-12-08,saddle back,short,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,23795,NaN,1.00,male,Unknown Mix,2019-12-08,2019-12-23,2019-12-08,yellow-brown,medium,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,23806,Amy,2.00,female,French Bulldog Mix,2019-12-10,2019-12-11,2019-12-11,black,short,small,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2932,118,Fodri,16.92,male,Unknown Mix,2003-12-25,2003-12-25,2006-03-22,yellow-brown,short,medium,no,no,yes,yes,no,yes,no,garden
2933,262,Csibi,17.33,female,Staffordshire Terrier Mix,2004-08-27,2004-08-27,2005-07-08,striped,short,large,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2934,4,Konrád,18.17,male,Unknown Mix,2005-09-21,2005-09-21,2005-10-26,black,short,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2935,141,Kölni,17.17,male,Unknown Mix,2004-11-27,2004-11-27,2005-05-02,black and brown,medium,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2936,248,Kedves,16.08,male,"German Shepherd Dog, Hound Mix",2005-04-02,2005-04-02,2005-06-30,sable,short,medium,yes,NaN,yes,NaN,yes,yes,NaN,both flat and garden

In [3]:
df2=pd.read_csv("/content/browser_version.csv")
df2  # As DataFrame has supervised ML

,Date,Chrome for Android,IE 8.0,Safari iPhone,Firefox 3.6,IE 9.0,IE 7.0,Android 0,IE 11.0,Safari iPad,...,Edge 98,Opera 31.0,Opera 68.0,Edge 99,Opera 22.0,Firefox 79.0,UC Browser 7.9,Opera 12.10,Opera 12.00,Other
0,2009-01,0.00,0.88,0.15,0.0,0.00,41.10,0.01,0.00,0.00,...,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.97
1,2009-02,0.00,1.17,0.16,0.0,0.00,40.48,0.01,0.00,0.00,...,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.93
2,2009-03,0.00,1.71,0.19,0.0,0.00,38.70,0.02,0.00,0.00,...,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.98
3,2009-04,0.00,3.63,0.21,0.0,0.00,36.47,0.02,0.00,0.00,...,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.99
4,2009-05,0.00,6.24,0.19,0.0,0.00,34.02,0.02,0.00,0.00,...,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,2022-03,36.17,0.02,13.98,0.0,0.03,0.00,0.64,0.32,0.91,...,0.78,0.01,0.02,3.09,0.0,0.01,0.0,0.0,0.0,7.72
159,2022-04,37.75,0.02,14.43,0.0,0.03,0.00,0.76,0.32,0.94,...,0.04,0.01,0.01,0.56,0.0,0.01,0.0,0.0,0.0,11.33
160,2022-05,38.79,0.01,14.59,0.0,0.03,0.00,0.70,0.59,0.88,...,0.02,0.01,0.01,0.06,0.0,0.01,0.0,0.0,0.0,8.77
161,2022-06,39.82,0.01,14.38,0.0,0.02,0.00,0.68,0.25,0.83,...,0.01,0.01,0.00,0.02,0.0,0.01,0.0,0.0,0.0,11.55
162,2022-07,40.29,0.01,14.70,0.0,0.03,0.00,0.72,0.23,0.83,...,0.01,0.01,0.00,0.01,0.0,0.01,0.0,0.0,0.0,9.26

In [6]:
df3=pd.read_csv("/content/Top vendors market share (2022 Q1).csv")
df3 # As DataFrame has a supervised ML

   Rank Manufacturer Market share
0     1       Lenovo       23.80%
1     2           HP       20.40%
2     3         Dell       17.70%
3     4        Apple        9.00%
4     5         Acer        7.20%
5     6         Asus        7.10%
6     7       Others       14.80%

In [7]:
df4=pd.read_csv("/content/Worldwide personal computer architectures by units sold (19751995).csv")
df4  # As DataFrame has an unsupervised ML

,Year,Annual sales,IBM PC compatible,Apple II,Macintosh,Atari 400/800,Atari ST,Commodore 64,Amiga,PET,Altair,TRS-80,NeXT,Other
0,1975,"5,000",0,0,0,0,0,0,0,0,"5,000",0,0,0
1,1976,"46,000",0,0,0,0,0,0,0,0,"6,000",0,0,"40,000"
2,1977,"150,000",0,600,0,0,0,0,0,"4,000","10,000","100,000",0,"50,000"
3,1978,"258,000",0,"7,600",0,0,0,0,0,"30,000","4,000","150,000",0,"100,000"
4,1979,"580,000",0,"35,000",0,"100,000",0,0,0,"45,000",0,"200,000",0,"200,000"
5,1980,"724,000",0,"78,000",0,"200,000",0,0,0,"90,000",0,"290,000",0,"424,000"
6,1981,"1,400,000","35,000","210,000",0,"300,000",0,0,0,"40,000",0,"250,000",0,"605,000"
7,1982,"2,800,000","240,000","279,000",0,"600,000",0,"200,000",0,"10,000",0,"300,000",0,"1,181,000"
8,1983,"4,920,000","1,300,000","420,000",0,"500,000",0,"2,000,000",0,0,0,"200,000",0,"500,000"
9,1984,"6,322,000","2,000,000","1,000,000","372,000","200,000",0,"2,500,000",0,0,0,"50,000",0,"200,000"
10,1985,"7,610,000","3,700,000","900,000","200,000","100,000","100,000","2,500,000","100,000",0,0,"10,000",0,0
11,1986,"9,000,000","5,020,000","700,000","380,000",0,"200,000","2,500,000","200,000",0,0,0,0,0
12,1987,"9,200,000","5,950,000","500,000","550,000",0,"400,000","1,500,000","300,000",0,0,0,0,0
13,1988,"15,000,000","11,900,000","200,000","900,000",0,"350,000","1,250,000","400,000",0,0,0,"12,000",0
14,1989,"21,000,000","17,550,000","200,000","1,100,000",0,"300,000","1,250,000","600,000",0,0,0,"12,000",0
15,1990,"20,000,000","16,838,000","100,000","1,300,000",0,"300,000","700,000","750,000",0,0,0,"12,000",0
16,1991,"18,750,000","14,399,000","100,000","2,100,000",0,"300,000","800,000","1,035,000",0,0,0,"16,000",0
17,1992,"20,800,000","18,300,000","100,000","2,500,000",0,"120,000","300,000","390,000",0,0,0,"10,000",0
18,1993,"31,050,000","27,750,000","30,000","3,300,000",0,"30,000","175,000","155,000",0,0,0,5,0
19,1994,"41,000,000","37,200,000",0,"3,800,000",0,0,0,"50,000",0,0,0,0,0
20,1995,"50,000,000","45,880,000",0,"4,120,000",0,0,0,"42,000",0,0,0,0,0
21,As of 1995,"260,615,000","208,062,000","4,860,200","20,622,000","2,000,000","2,100,000","15,675,000","4,022,000","219,000","25,000","1,550,000","62,005","3,300,000"

In [8]:
df5=pd.read_csv("/content/Mall_Customers.csv")
df5  # As DataFrame has supervised ML

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [3]:
df6=pd.read_csv("/content/financials.csv")
df6  #  As DataFrame has an unsupervised

,Symbol,Name,Sector,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book,SEC Filings
0,MMM,3M Company,Industrials,222.89,24.31,2.332862,7.92,259.77,175.490,1.387211e+11,9.048000e+09,4.390271,11.34,http://www.sec.gov/cgi-bin/browse-edgar?action...
1,AOS,A.O. Smith Corp,Industrials,60.24,27.76,1.147959,1.70,68.39,48.925,1.078342e+10,6.010000e+08,3.575483,6.35,http://www.sec.gov/cgi-bin/browse-edgar?action...
2,ABT,Abbott Laboratories,Health Care,56.27,22.51,1.908982,0.26,64.60,42.280,1.021210e+11,5.744000e+09,3.740480,3.19,http://www.sec.gov/cgi-bin/browse-edgar?action...
3,ABBV,AbbVie Inc.,Health Care,108.48,19.41,2.499560,3.29,125.86,60.050,1.813863e+11,1.031000e+10,6.291571,26.14,http://www.sec.gov/cgi-bin/browse-edgar?action...
4,ACN,Accenture plc,Information Technology,150.51,25.47,1.714470,5.44,162.60,114.820,9.876586e+10,5.643228e+09,2.604117,10.62,http://www.sec.gov/cgi-bin/browse-edgar?action...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,XYL,Xylem Inc.,Industrials,70.24,30.94,1.170079,1.83,76.81,46.860,1.291502e+10,7.220000e+08,2.726209,5.31,http://www.sec.gov/cgi-bin/browse-edgar?action...
501,YUM,Yum! Brands Inc,Consumer Discretionary,76.30,27.25,1.797080,4.07,86.93,62.850,2.700330e+10,2.289000e+09,6.313636,212.08,http://www.sec.gov/cgi-bin/browse-edgar?action...
502,ZBH,Zimmer Biomet Holdings,Health Care,115.53,14.32,0.794834,9.01,133.49,108.170,2.445470e+10,2.007400e+09,3.164895,2.39,http://www.sec.gov/cgi-bin/browse-edgar?action...
503,ZION,Zions Bancorp,Financials,50.71,17.73,1.480933,2.60,55.61,38.430,1.067068e+10,0.000000e+00,3.794579,1.42,http://www.sec.gov/cgi-bin/browse-edgar?action...
504,ZTS,Zoetis,Health Care,71.51,32.80,0.682372,1.65,80.13,52.000,3.599111e+10,1.734000e+09,9.280896,18.09,http://www.sec.gov/cgi-bin/browse-edgar?action...

In [4]:
df7=pd.read_csv("/content/National_Stock_Exchange_of_India_Ltd.csv")
df7  # As DataFrame has an unsupervised

,Symbol,Open,High,Low,LTP,Chng,% Chng,Volume (lacs),Turnover (crs.),52w H,52w L,365 d % chng,30 d % chng
0,ADANIPORTS,750,766,713.25,715,-47.45,-6.22,72.20,532.63,901,384.4,79.22,-4.65
1,ASIANPAINT,"3,101.00","3,167.35","3,091.00","3,138.00",-6.25,-0.20,10.29,322.53,"3,505.00","2,117.15",45.66,5.66
2,AXISBANK,669,674.9,660.45,661,-18.90,-2.78,102.53,684,866.9,568.4,10.19,-21.49
3,BAJAJ-AUTO,"3,370.00","3,383.50","3,320.00","3,335.00",-56.70,-1.67,3.42,114.59,"4,361.40","3,041.00",9.30,-12.05
4,BAJAJFINSV,"17,200.00","17,237.20","16,610.00","16,684.00",-684.85,-3.94,3.42,576.79,"19,325.00","8,273.70",91.38,-9.10
5,BAJFINANCE,"7,021.00","7,047.90","6,775.00","6,780.00",-345.80,-4.85,16.89,"1,161.63","8,050.00","4,362.00",44.57,-13.69
6,BHARTIARTL,763,763,733.1,735.85,-29.30,-3.83,111.43,830.06,781.8,454.11,58.55,5.70
7,BPCL,397.15,397.2,375,377.4,-22.70,-5.67,100.23,383.54,503,357,-1.22,-12.45
8,BRITANNIA,"3,560.00","3,635.10","3,533.95","3,566.60",-6.80,-0.19,3.73,133.23,"4,153.00","3,317.30",0.30,-3.42
9,CIPLA,892,976.05,890.65,965,65.05,7.23,144.59,"1,380.90","1,005.00",726.5,31.89,6.34
10,COALINDIA,157.75,159.4,155.35,155.9,-2.65,-1.67,118.30,185.5,203.8,123.25,25.78,-10.94
11,DIVISLAB,"4,770.00","5,077.70","4,756.75","4,940.00",140.20,2.92,15.71,775.37,"5,425.10","3,153.30",42.39,-1.57
12,DRREDDY,"4,580.00","4,820.00","4,576.15","4,750.00",158.40,3.45,10.72,508.97,"5,614.60","4,135.00",-1.17,1.80
13,EICHERMOT,"2,495.00","2,506.10","2,421.50","2,440.75",-79.65,-3.16,5.55,136.56,"3,037.00","2,303.70",-5.95,-5.77
14,GRASIM,"1,757.30","1,757.85","1,679.00","1,685.80",-80.95,-4.58,7.48,127.84,"1,893.00",840.05,99.95,-3.08
15,HCLTECH,"1,120.00","1,126.00","1,103.30","1,111.65",-13.15,-1.17,22.07,246.06,"1,377.75",814.35,34.79,-4.73
16,HDFC,"2,820.35","2,856.00","2,723.00","2,745.00",-122.75,-4.28,33.53,927.88,"3,021.10","2,179.30",25.27,-5.72
17,HDFCBANK,"1,500.00","1,506.70","1,485.00","1,489.50",-36.45,-2.39,93.12,"1,394.10","1,725.00","1,342.00",6.18,-9.88
18,HDFCLIFE,685,689,667.1,669.75,-19.05,-2.77,22.37,151.4,775.65,617.4,0.70,-2.94
19,HEROMOTOCO,"2,580.00","2,589.70","2,505.15","2,526.80",-67.90,-2.62,6.85,174.04,"3,629.05","2,505.15",-16.02,-6.43
20,HINDALCO,441.8,442.7,414.7,417.7,-29.35,-6.57,148.26,631.93,551.85,220.35,86.93,-14.06
21,HINDUNILVR,"2,344.00","2,365.00","2,325.20","2,340.90",-8.15,-0.35,24.51,572.85,"2,859.30","2,120.00",9.60,-3.94
22,ICICIBANK,739,742.05,718.6,720.45,-30.60,-4.07,189.88,"1,385.86",867,465.8,52.41,-13.14
23,INDUSINDBK,951,956.95,898,899.95,-59.35,-6.19,67.46,622.74,"1,242.00",789,5.25,-22.08
24,INFY,"1,702.55","1,718.35","1,684.00","1,689.55",-32.85,-1.91,44.94,764.67,"1,848.00","1,091.00",51.44,-0.83
25,IOC,125.6,125.6,120.5,121.15,-4.50,-3.58,77.25,94.57,141.5,84,41.28,-7.87
26,ITC,228.9,230.05,223.1,223.6,-7.70,-3.33,270.27,610.54,265.3,192.4,15.35,-5.53
27,JSWSTEEL,668.25,672.55,624.25,630,-50.90,-7.48,89.22,574.61,776.5,336,86.25,-9.27
28,KOTAKBANK,"2,002.00","2,007.00","1,955.10","1,960.00",-75.10,-3.69,26.48,522.52,"2,253.00","1,626.00",5.24,-11.35
29,LT,"1,820.00","1,841.75","1,768.60","1,781.00",-68.90,-3.72,27.97,502.81,"1,981.75","1,092.00",59.59,-0.85
30,M&M,885,885,843,855.05,-36.15,-4.06,39.34,338.08,979,660.25,18.77,-4.42
31,MARUTI,"7,520.00","7,520.00","7,130.00","7,150.00",-422.50,-5.58,11.55,840.81,"8,368.00","6,400.00",1.34,-2.02
32,NESTLEIND,"19,148.85","19,434.10","18,982.50","19,250.00",71.95,0.38,0.56,108.61,"20,609.15","16,002.10",9.87,0.17
33,NTPC,133.2,134.05,128,128.65,-6.55,-4.84,133.24,173.94,152.1,88.15,36.93,-10.16
34,ONGC,152.25,152.25,146.25,147.75,-7.35,-4.74,231.36,344.33,172.75,77.05,82.86,-9.41
35,POWERGRID,204.05,204.95,200.8,202.5,-1.75,-0.86,96.11,195.09,209.95,136.88,3.69,6.36
36,RELIANCE,"2,467.80","2,477.60","2,401.50","2,405.10",-87.85,-3.52,72.75,"1,770.19","2,751.35","1,830.00",23.48,-9.62
37,SBILIFE,"1,154.00","1,154.00","1,105.25","1,130.85",-28.65,-2.47,23.16,262.43,"1,273.90",825.2,33.19,-3.52
38,SBIN,486.25,487.9,467.1,470,-20.55,-4.19,263.06,"1,249.55",542.3,240.15,93.42,-8.30
39,SHREECEM,"26,450.00","26,539.90","25,812.00","25,900.00",-770.50,-2.89,0.30,76.94,"32,048.00","22,531.00",9.29,-6.76
40,SUNPHARMA,775,798.9,762,767.25,-15.65,-2.00,54.33,424.05,851,502.3,51.57,-5.69
41,TATACONSUM,800.2,805,763.15,769.9,-37.90,-4.69,26.17,203.32,889,505.05,49.55,-4.82
42,TATAMOTORS,486,486.75,458,459.4,-33.35,-6.77,517.88,"2,430.36",536.7,156.7,167.95,-9.68
43,TATASTEEL,"1,157.90","1,159.50","1,106.25","1,110.25",-63.40,-5.40,106.46,"1,200.79","1,534.50",539.5,105.13,-17.37
44,TCS,"3,425.00","3,490.00","3,411.90","3,439.20",-6.70,-0.19,19.41,670.58,"3,989.90","2,624.45",27.32,-1.25
45,TECHM,"1,544.00","1,550.00","1,510.15","1,519.00",-40.35,-2.59,15.22,232.97,"1,630.00",846.7,76.17,-2.83
46,TITAN,"2,377.80","2,385.10","2,285.05","2,293.00",-104.80,-4.37,12.89,298.54,"2,677.90","1,300.35",75.45,-6.59
47,ULTRACEMCO,"7,550.00","7,599.00","7,370.10","7,398.45",-210.35,-2.76,2.66,198.32,"8,269.00","4,770.00",53.50,1.78
48,UPL,726,726,701,703.5,-23.80,-3.27,24.82,176.35,864.7,414.15,68.06,-1.37
49,WIPRO,632,634.4,619.65,621.3,-15.40,-2.42,41.39,259.37,739.85,346.25,77.51,-7.01

In [5]:
df8=pd.read_csv("/content/KnowledgeBase Pdf Files - Crypto Currencies.csv")
df8   #As DataFrame has supervised

,Topic,Link,Total = 73 papers across the 3
0,The impact of the Russian-Ukrainian war on glo...,https://www.sciencedirect.com/science/article/...,NaN
1,Information in Financial Markets and Its Real ...,https://academic.oup.com/rof/article/27/1/1/66...,NaN
2,Taxing cryptocurrencies,https://academic.oup.com/oxrep/article/39/3/47...,NaN
3,Cryptocurrencies: market analysis and perspect...,https://link.springer.com/article/10.1007/s408...,NaN
4,A Statistical Analysis of Cryptocurrencies,https://www.mdpi.com/1911-8074/10/2/12,NaN
5,Privacy-Preserving Multi-Party Cross-Chain Tra...,https://www.mdpi.com/2410-387X/8/1/6,NaN
6,Unveiling Cryptocurrency Impact on Financial M...,https://www.mdpi.com/1911-8074/17/2/58,NaN
7,Decentralization Is Good or Not? Defending Con...,https://www.mdpi.com/2813-5288/2/1/1,NaN
8,Review of Blockchain’s Role in E-Commerce Tran...,https://www.mdpi.com/2073-431X/13/1/27,NaN
9,Time Series Forecasting Utilizing Automated Ma...,https://www.mdpi.com/2078-2489/15/1/39,NaN
10,Is Monetary Policy a Driver of Cryptocurrencie...,https://www.mdpi.com/2225-1146/12/1/2,NaN
11,Time-Varying Bidirectional Causal Relationship...,https://www.mdpi.com/1911-8074/17/1/19,NaN
12,Blockchain Architectures for the Digital Econo...,https://www.mdpi.com/2071-1050/16/1/442,NaN
13,Blockchain-Powered Gaming: Bridging Entertainm...,https://www.mdpi.com/2073-431X/13/1/14,NaN
14,Unveiling the Influencing Factors of Cryptocur...,https://www.mdpi.com/1911-8074/17/1/12,NaN
15,Using Machine Learning of Artificial Intellige...,https://www.mdpi.com/2673-4591/55/1/12,NaN
16,Enhancing Cryptocurrency Price Forecasting by ...,https://www.mdpi.com/1999-4893/16/12/542,NaN
17,Navigating the Future: Blockchain’s Impact on ...,https://www.mdpi.com/2071-1050/15/24/16887,NaN
18,Performance Comparison of Directed Acyclic Gra...,https://www.mdpi.com/2073-431X/12/12/257,NaN
19,Are Cryptocurrency Forks Wealth Creating?,https://www.mdpi.com/1911-8074/16/12/510,NaN
20,Chance or Chaos? Fractal Geometry Aimed to Ins...,https://www.mdpi.com/2504-3110/7/12/870,NaN
21,Fintech Adoption Factors: A Study on an Educat...,https://www.mdpi.com/2075-4698/13/12/262,NaN
22,Thermodynamic Analysis of Financial Markets: M...,https://www.mdpi.com/1099-4300/26/1/24,NaN
23,Using Big Data Analytics and Heatmap Matrix Vi...,https://www.mdpi.com/2076-3417/14/1/154,NaN
24,Threshold/Multi Adaptor Signature and Their Ap...,https://www.mdpi.com/2079-9292/13/1/76,NaN
25,How Should Cryptocurrencies Be Defined and Rep...,https://www.mdpi.com/1911-8074/17/1/3,NaN
26,Enhancing Cryptocurrency Price Forecasting by ...,https://www.mdpi.com/1999-4893/16/12/542,NaN
27,Active Learning in the Detection of Anomalies ...,https://www.mdpi.com/2504-4990/5/4/84,NaN
28,Blockchain in Peer-to-Peer Platforms: Enhancin...,https://www.mdpi.com/2071-1050/15/22/15968,NaN
29,The Relationship between a Company’s Cryptocur...,https://www.mdpi.com/2071-1050/15/23/16188,NaN
30,Blockchain in Peer-to-Peer Platforms: Enhancin...,https://www.mdpi.com/2071-1050/15/22/15968,NaN
31,Optimization of Cryptocurrency Algorithmic Tra...,https://www.mdpi.com/2504-2289/7/4/174,NaN

In [6]:
df9=pd.read_csv("/content/jobs_in_data.csv")
df9

,work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size
0,2023,Data DevOps Engineer,Data Engineering,EUR,88000,95012,Germany,Mid-level,Full-time,Hybrid,Germany,L
1,2023,Data Architect,Data Architecture and Modeling,USD,186000,186000,United States,Senior,Full-time,In-person,United States,M
2,2023,Data Architect,Data Architecture and Modeling,USD,81800,81800,United States,Senior,Full-time,In-person,United States,M
3,2023,Data Scientist,Data Science and Research,USD,212000,212000,United States,Senior,Full-time,In-person,United States,M
4,2023,Data Scientist,Data Science and Research,USD,93300,93300,United States,Senior,Full-time,In-person,United States,M
...,...,...,...,...,...,...,...,...,...,...,...,...
9350,2021,Data Specialist,Data Management and Strategy,USD,165000,165000,United States,Senior,Full-time,Remote,United States,L
9351,2020,Data Scientist,Data Science and Research,USD,412000,412000,United States,Senior,Full-time,Remote,United States,L
9352,2021,Principal Data Scientist,Data Science and Research,USD,151000,151000,United States,Mid-level,Full-time,Remote,United States,L
9353,2020,Data Scientist,Data Science and Research,USD,105000,105000,United States,Entry-level,Full-time,Remote,United States,S
9354,2020,Business Data Analyst,Data Analysis,USD,100000,100000,United States,Entry-level,Contract,Remote,United States,L

In [7]:
df10=pd.read_csv("/content/final_data.csv")
df10  # As dataframe has unsupervised ML.

,Company_Name,Class,Designation,Location,Total_applicants,LinkedIn_Followers,Level,Involvement,Employee_count,Industry,...,REACTJS,AI,UI,TABLEAU,NODEJS,EXCEL,POWER BI,SELENIUM,HTML,ML
0,Wipro,Class 3,Project Manager,Maharashtra,0,6737300,Full-time,Entry level,10001,IT Services and IT Consulting,...,0,1,1,0,0,1,0,0,0,1
1,Wipro,Class 3,Project Manager,Delhi,121,6737300,Full-time,Entry level,10001,IT Services and IT Consulting,...,0,1,1,0,0,1,0,0,0,1
2,Wipro,Class 3,Project Manager,Delhi,0,6737300,Full-time,Entry level,10001,IT Services and IT Consulting,...,0,1,1,0,0,1,0,0,0,1
3,Wipro,Class 3,Administrator,Telangana,0,6737300,Full-time,Mid-Senior level,10001,IT Services and IT Consulting,...,0,1,1,0,0,1,0,0,0,0
4,Wipro,Class 3,Project Manager,Maharashtra,119,6737300,Full-time,Entry level,10001,IT Services and IT Consulting,...,0,1,1,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
806,Infosys,Class 3,Java Developer (5-8 yrs) Indore,Madhya Pradesh,44,6790011,Full-time,Mid-Senior level,10001,IT Services and IT Consulting,...,0,1,1,0,0,1,0,0,0,0
807,Infosys,Class 3,Technology Analyst - NodeJs (3-5 years) - Bhub...,Odisha,77,6790011,Full-time,Entry level,10001,IT Services and IT Consulting,...,0,1,1,0,1,0,0,0,0,0
808,Genpact,Class 1,Hiring for OTC- JAIPUR,Rajasthan,47,2519518,Full-time,Entry level,10001,IT Services and IT Consulting,...,0,1,0,0,0,1,0,0,0,0
809,Genpact,Class 1,C++ Developer,Telangana,72,2519518,Full-time,Mid-Senior level,10001,IT Services and IT Consulting,...,0,1,1,0,0,0,0,0,0,0
810,Genpact,Class 1,Hiring for RTR- Jaipur,Rajasthan,133,2519518,Full-time,Associate,10001,IT Services and IT Consulting,...,0,1,1,0,0,1,0,0,0,0